name: Generate Snake

# Grant write permission to push generated SVGs to repository
permissions:
  contents: write

on:
  # Run automatically every 12 hours
  schedule:
    - cron: "0 */12 * * *"
  # Allows manual triggering of the workflow from the Actions tab
  workflow_dispatch:
  # Run on every push to the main branch
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # Generates the snake animation
      - name: generate-snake-game-from-github-contribution-grid
        uses: Platane/snk@v3.5.0
        with:
          github_user_name: ${{ github.repository_owner }}
          # Define the files you want to generate
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      # Pushes the generated SVGs to the 'output' branch
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
